### ISSUE TITLE
關於setDarkMode()

### ISSUE THREAD

**Issue by tenSunFree** [xmuSistone/VegaLayoutManager#13]
![2017-09-29_141425](https://user-images.githubusercontent.com/23090085/31003284-76cec5d6-a521-11e7-864e-7cbea1311c47.jpg)

![2017-09-29_141627](https://user-images.githubusercontent.com/23090085/31003289-7ab2e402-a521-11e7-81c8-8cdb4a50e82c.jpg)

開啟2的方式, 是要先透過1 
然後2會接受到傳過來的 darkMode參數為true
既然darkMode參數 恆為true, 3的部分 還有需要判斷嗎?

還是說有其它原因?

**Comment by xmuSistone** [comment]
这个是原先工具类直接拿过来用的。一个项目，darkMode既有true又有false，用这个会比较方便。如果仅仅是局限在这一个仓库，代码确实没必要有太灵活的个性化定制，但是这些不重要，因为有些跑题了。这个仓库的主要意图是LayoutManager.
