### ISSUE TITLE
Problems during scrolling with recyling views 

### ISSUE THREAD

**Issue by davidmarinangeli** [xmuSistone/VegaLayoutManager#15]
As you can see from the screenshots, whenever I scroll my list down and then i go up again, there are some rendering problems.

Are these known problems? 

![inkedscreenshot_2017-10-17-23-17-38_li](https://user-images.githubusercontent.com/19487461/31690382-de0f100a-b392-11e7-8b0d-3542a82767eb.jpg)
![inkedscreenshot_2017-10-17-23-18-21_li](https://user-images.githubusercontent.com/19487461/31690383-de2ef03c-b392-11e7-9920-242420f87b3e.jpg)

**Comment by xmuSistone** [comment]
It may not be the problem of this repository. Replace the VegaLayoutManager with LinearLayoutManager, and you will have the same problem. Please check your adapter logic.

**Comment by davidmarinangeli** [comment]
No, it isn't. I had LinearLayoutManager and I hadn't these problems.

**Comment by xmuSistone** [comment]
try the latest code i commit today. if problem still exists, mind if copy the key code of adapter and paste here?

**Comment by davidmarinangeli** [comment]
Ok it works! Thanks a lot. I'll keep using your libraries so you will see me around 😛 

Thanks again.
