### ISSUE TITLE
2.When I use the VegaLayoutManager, The notifyDataSetChanged is useless.

### ISSUE THREAD

**Issue by hexiangbing** [xmuSistone/VegaLayoutManager#17]
Hello,When I use the VegaLayoutManager, The notifyDataSetChanged is useless, And it need i scroll the recyclerview，then it can notify.

**Comment by xmuSistone** [comment]
Please try the latest library code, not from gradle dependency (gradle is not consistent with the latest code). If problem still exists, mind if copy the key code of using adapter and paste here?

**Comment by xmuSistone** [comment]
gradle version has already been updated to v1.0.2, please update it if you use gradle dependency.

**Comment by hexiangbing** [comment]
I will try it.Thank you.






在 2017-10-20 14:50:01，"stone" <notifications@github.com> 写道：


Closed #17.

**Comment by hexiangbing** [comment]
Thank you. I will try it.
