### ISSUE TITLE
Notifying adapter left duplicate items in list after remove one item .

### ISSUE THREAD

**Issue by diaz9557** [xmuSistone/VegaLayoutManager#20]
On Notifying adapter on remove it duplicates the row item , When using multiple Item Types layout . Please look into issue .

**Comment by xmuSistone** [comment]
would u please describe it with more details?

**Comment by diaz9557** [comment]
When i am calling NotifyDatasetChange as below
`  list.remove(forPosition);
            if (rv_Stack.getAdapter() != null)
                rv_Stack.getAdapter().notifyDataSetChanged();`

the next item from removed position appear twice.

**Comment by xmuSistone** [comment]
@diaz9557 i fixed this bug just now, u can try the latest code in the library module. Gradle dependency will be updated later.

**Comment by diaz9557** [comment]
Thanks dude .I'll try

**Comment by xmuSistone** [comment]
@diaz9557 Kitkat has this problem, I submitted new code just now. please try it again when you have spare time.
