### ISSUE TITLE
Different behaviour On Kitkat  and above Kikat

### ISSUE THREAD

**Issue by diaz9557** [xmuSistone/VegaLayoutManager#21]
I have tested VegaLayoutManager in Kitkat and above . There is a behavior difference .

    On kitkat - On scroll to bottom, the last items scrolls to the top .
    Above Kitkat - The last item remains on the bottom of recycler view .

Is this the issue with RecyclerView in Kitkat or some other ?

**Comment by xmuSistone** [comment]
Yeah, it's a bug. I'm fixing it now.

**Comment by xmuSistone** [comment]
@diaz9557 Kitkat has this problem, I submitted new code just now. please try it again when you have spare time.

**Comment by diaz9557** [comment]
Thx . will check it .
