### ISSUE TITLE
Different behaviour On Different OS

### ISSUE THREAD

**Issue by diaz9557** [xmuSistone/VegaLayoutManager#22]
Its the same issue as [issue21](https://github.com/xmuSistone/VegaLayoutManager/issues/21l).I am adding it cause the issue was not resolved previously.  Before i have tested it on kitkat and above . Now its showing the kitkat like behavior on Android N too. I have tested on MOTO Z play.

On kitkat/Android N - On scroll to bottom, the last items scrolls to the top .
Above Kitkat - The last item remains on the bottom of recycler view .

Can it be resolve? or its OS dependent . 
Thx 
Diaz

**Comment by xmuSistone** [comment]
i did not get this problem. how does it appear?

**Comment by diaz9557** [comment]
Let me explain it. If i have 10 items in list . and 2 items are visible at a time on screen . 
Now if i scroll the list to bottom there is only single item viewable on screen which is the 10th one(In kitkat and Android N (These are the only OS i have tested On)).

In other os in same scenario 2 items are visible . which are 9th and 10th .

**Comment by xmuSistone** [comment]
let me check.

**Comment by diaz9557** [comment]
I have tested the sample you provided. It doesn't show the same behavior. I think your code is working fine. Must be some problem with my custom views.
Thx for support .

**Comment by xmuSistone** [comment]
@diaz9557 ok
