### ISSUE TITLE
You must override onLayoutChildren(Recycler recycler, State state) 

### ISSUE THREAD

**Issue by anantshah93** [xmuSistone/VegaLayoutManager#23]
After scrolling and keep screen visible without touching after 2-3 min it hides recycler view items. and error is 

E/RecyclerView: You must override onLayoutChildren(Recycler recycler, State state)

when u touch again it shows recyclerview items API23 device i m using.

If you want to check in android application this is link -
https://play.google.com/store/apps/details?id=io.app.cryptocoins
pls check (select currency)

**Comment by xmuSistone** [comment]
please try the latest code.
