### ISSUE TITLE
demo显示无内容

### ISSUE THREAD

**Issue by GentlemanDemo** [xmuSistone/VegaLayoutManager#39]
把demo下载来运行，结果什么都不展示。把recyclerView.setLayoutManager(new VegaLayoutManager());换成recyclerView.setLayoutManager(new LinearLayoutManager(this));有内容，但是没有了效果

**Comment by xmuSistone** [comment]
@GentlemanDemo 直接下载Apk安装也不行么？
我这边是没有适配问题的？所以问下你的手机型号是？还是模拟器？

**Comment by GentlemanDemo** [comment]
直接下载Apk安装在模拟器真机都行的，但是下载代码，启动运行就不行

**Comment by xmuSistone** [comment]
稍等，我pull代码看看

**Comment by xmuSistone** [comment]
@GentlemanDemo 我这边跑代码是没问题的，有个小意外是OV手机闪退(instant run引起)，其它也没什么问题。这中间，我更新了gradle版本，删掉了bintray，所以，不知道是不是版本问题引起的空白。你可以再试试看，如果还有问题，可以把手机型号发我看下。
