### ISSUE TITLE
快速闪烁问题

### ISSUE THREAD

**Issue by iota9star** [xmuSistone/VegaLayoutManager#8]
如题，不清楚原因，一动就闪烁个不停
![baidushurufa_2017-9-27_16-50-50](https://user-images.githubusercontent.com/21272154/30904263-0c416bc0-a3a4-11e7-85c9-60a1654339d3.png)

![baidushurufa_2017-9-27_16-49-15](https://user-images.githubusercontent.com/21272154/30904194-d9569348-a3a3-11e7-8ade-976bc1c8b767.png)

**Comment by iota9star** [comment]
添加有refreshlayout 和 footer  footer一加载更多，就开始闪烁

**Comment by xmuSistone** [comment]
这个不是java代码吧？onLayoutChildren已经被复写，日志部分让人疑惑

**Comment by XngPro** [comment]
@xmuSistone 去掉 super.onLayoutChildren(recycler, state);  PR 已修改

**Comment by xmuSistone** [comment]
嗯好。

**Comment by iota9star** [comment]
我使用[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)这个，一加载更多就会开始闪烁，百分百复现，不知道是这个SmartRefreshLayout的问题还是啥，但是这个包裹的recyclerview应该不会影响recyclerview吧？不过没有仔细看，只是体验一下这个的效果，打扰了

**Comment by xmuSistone** [comment]
@iota9star 用原生的SwipeRefreshLayout没问题。

**Comment by iota9star** [comment]
上拉加载更多的时候就开始出现，强烈闪烁，并且加载完成后，所有条目都不可见，如果原生没有问题的话应该是两者之间有冲突，谢谢回复

**Comment by xmuSistone** [comment]
LayoutManager中，我是处理了recyclerView传过来的dy信息，但是这个dy信息，也只是recyclerView提供过来的。所以，我感觉SmartRefreshLayout对SwipeRefreshLayout的封装，并没有按安卓标准来。当然，此仓库自定义LayoutManager不够健壮，无法兼容众多自封的SwipeRefreshLayout。如果站在解决问题的角度考虑，上拉加载可暂时去除，用recyclerView自身的getView去加载下一页。我是这样感觉的。后面有时间，我可以看下能否适配的了这个SmartRefreshLayout。
