### ISSUE TITLE
How can I modify the layout manager to achieve a horizontal scrolling effect?

### ISSUE THREAD

**Issue by aWayOfLife** [xmuSistone/VegaLayoutManager#9]
Thanks for the amazing library. I was wondering if we could achieve this effect for a horizontally scrolling recycler view like it's shown in the attachment.
![horizontal scroll](https://user-images.githubusercontent.com/17787862/30910509-af4a4f32-a3a2-11e7-98f6-b5f650a561a8.gif)

**Comment by xmuSistone** [comment]
Actually, there has some other repositories which have done this work. Such as this one: [clik here](https://github.com/Ramotion/cardslider-android). And you may need to know more about LayoutManager to improve and optimize the fluency.
